packages:
  - packages/shared/*
  - packages/web/*
  - packages/ai/**
  - apps/*
  - services/*
  - scripts
catalog:
  "@types/fs-extra": ^11.0.4
  "@types/node": ^22.15.3
  "@vitejs/plugin-vue": ^5.2.3
  "@vitejs/plugin-vue-jsx": ^4.1.2
  "@vue/compiler-dom": ^3.5.13
  "@vue/test-utils": ^2.4.6
  "@vueuse/core": ^13.1.0
  "@vueuse/integrations": ^13.1.0
  cross-env: ^7.0.3
  dotenv: ^16.5.0
  eslint: ^9.25.1
  husky: ^9.1.7
  jsdom: ^26.1.0
  pinia: 2.3.0
  pinia-plugin-persistedstate: ^4.2.0
  rimraf: ^6.0.1
  tsup: ^8.4.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.1.0-beta.12
  vite: ^6.3.3
  vitest: ^3.1.2
  vue: ^3.5.13
  vue-i18n: ^11.1.3
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
