packages:
  - packages/shared/*
  - packages/web/*
  - packages/ai/**
  - apps/*
  - services/*
  - scripts
catalog:
  "@changesets/cli": ^2.29.2
  "@commitlint/cli": ^19.8.0
  "@commitlint/config-conventional": ^19.8.0
  "@iconify/json": ^2.2.332
  "@iconify/vue": 4.1.2
  "@kirklin/eslint-config": ^5.0.0
  "@kirklin/logger": 0.0.2
  "@kirklin/palette": ^0.2.1
  "@kirklin/reset-css": ^0.0.6
  "@tanstack/query-persist-client-core": ^5.74.7
  "@tanstack/query-sync-storage-persister": ^5.74.7
  "@tanstack/vue-query": ^5.74.7
  "@tanstack/vue-table": ^8.21.3
  "@types/crypto-js": ^4.2.2
  "@types/fs-extra": ^11.0.4
  "@types/lodash-es": ^4.17.12
  "@types/node": ^22.15.3
  "@types/nprogress": ^0.2.3
  "@types/prompts": ^2.4.9
  "@types/qs": ^6.9.18
  "@unocss/eslint-plugin": ^66.1.0-beta.12
  "@vitejs/plugin-vue": ^5.2.3
  "@vitejs/plugin-vue-jsx": ^4.1.2
  "@vitest/coverage-v8": ^3.1.2
  "@vue/compiler-dom": ^3.5.13
  "@vue/test-utils": ^2.4.6
  "@vueuse/core": ^13.1.0
  algorithm-snowflake: ^0.0.0
  animate.css: ^4.1.1
  axios: ^1.9.0
  bumpp: ^10.1.0
  colord: ^2.9.3
  cross-env: ^7.0.3
  crypto-js: ^4.2.0
  dayjs: ^1.11.13
  destr: ^2.0.5
  detect-mobile: ^0.0.0
  directory-tree: ^3.5.2
  dotenv: ^16.5.0
  echarts: ^5.6.0
  eslint: ^9.25.1
  eslint-plugin-format: ^1.0.1
  eslint-plugin-vuejs-accessibility: ^2.4.1
  esno: ^4.8.0
  execa: ^9.5.2
  fs-extra: ^11.3.0
  h3: ^1.15.3
  headless-highlighter: ^0.0.0
  husky: ^9.1.7
  iso-639-1: ^3.1.5
  jsdom: ^26.1.0
  lint-staged: ^15.5.1
  lodash-es: ^4.17.21
  naive-ui: 2.40.1
  nitropack: ^2.11.11
  npm-run-all: ^4.1.5
  nprogress: ^0.2.0
  path-to-regexp: ^8.2.0
  pinia: ^3.0.2
  pinia-plugin-persistedstate: ^4.2.0
  pkg-types: ^2.1.0
  pnpm: ^10.10.0
  prompts: ^2.4.2
  qs: ^6.14.0
  rimraf: ^6.0.1
  rollup-plugin-visualizer: ^5.14.0
  taze: ^19.0.4
  treeify: ^1.1.0
  tsup: ^8.4.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.1.0-beta.12
  unocss-preset-chinese: ^0.3.3
  unocss-preset-ease: ^0.0.4
  unplugin-auto-import: ^19.1.2
  unplugin-config: ^0.1.5
  unplugin-vue-components: ^28.5.0
  vite: ^6.3.3
  vite-plugin-inspect: ^11.0.1
  vite-plugin-pwa: ^1.0.0
  vite-plugin-vue-devtools: ^7.7.6
  vitest: ^3.1.2
  vue: ^3.5.13
  vue-echarts: ^7.0.3
  vue-i18n: ^11.1.3
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
