/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CAAppLogo: typeof import('@celeris/components')['CAAppLogo']
    CAAppNaiveUIProvider: typeof import('@celeris/components')['CAAppNaiveUIProvider']
    NButton: typeof import('@celeris/ca-components')['NButton']
    NConfigProvider: typeof import('@celeris/ca-components')['NConfigProvider']
    NDialogProvider: typeof import('@celeris/ca-components')['NDialogProvider']
    NDivider: typeof import('@celeris/ca-components')['NDivider']
    NDrawer: typeof import('@celeris/ca-components')['NDrawer']
    NDrawerContent: typeof import('@celeris/ca-components')['NDrawerContent']
    NForm: typeof import('@celeris/ca-components')['NForm']
    NFormItem: typeof import('@celeris/ca-components')['NFormItem']
    NGlobalStyle: typeof import('@celeris/ca-components')['NGlobalStyle']
    NInput: typeof import('@celeris/ca-components')['NInput']
    NLoadingBarProvider: typeof import('@celeris/ca-components')['NLoadingBarProvider']
    NMenu: typeof import('@celeris/ca-components')['NMenu']
    NMessageProvider: typeof import('@celeris/ca-components')['NMessageProvider']
    NNotificationProvider: typeof import('@celeris/ca-components')['NNotificationProvider']
    NResult: typeof import('@celeris/ca-components')['NResult']
    NScrollbar: typeof import('@celeris/ca-components')['NScrollbar']
    NSpace: typeof import('@celeris/ca-components')['NSpace']
    NSwitch: typeof import('@celeris/ca-components')['NSwitch']
    NTooltip: typeof import('@celeris/ca-components')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
