/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CAAppLogo: typeof import('@celeris/components')['CAAppLogo']
    CAAppNaiveUIProvider: typeof import('@celeris/components')['CAAppNaiveUIProvider']
    CACharts: typeof import('@celeris/components')['CACharts']
    CAIcon: typeof import('@celeris/components')['CAIcon']
    NAvatar: typeof import('@celeris/ca-components')['NAvatar']
    NBreadcrumb: typeof import('@celeris/ca-components')['NBreadcrumb']
    NBreadcrumbItem: typeof import('@celeris/ca-components')['NBreadcrumbItem']
    NButton: typeof import('@celeris/ca-components')['NButton']
    NCard: typeof import('@celeris/ca-components')['NCard']
    NCheckbox: typeof import('@celeris/ca-components')['NCheckbox']
    NCol: typeof import('@celeris/ca-components')['NCol']
    NColorPicker: typeof import('@celeris/ca-components')['NColorPicker']
    NConfigProvider: typeof import('@celeris/ca-components')['NConfigProvider']
    NDialogProvider: typeof import('@celeris/ca-components')['NDialogProvider']
    NDivider: typeof import('@celeris/ca-components')['NDivider']
    NDrawer: typeof import('@celeris/ca-components')['NDrawer']
    NDrawerContent: typeof import('@celeris/ca-components')['NDrawerContent']
    NDropdown: typeof import('@celeris/ca-components')['NDropdown']
    NEl: typeof import('@celeris/ca-components')['NEl']
    NForm: typeof import('@celeris/ca-components')['NForm']
    NFormItem: typeof import('@celeris/ca-components')['NFormItem']
    NGlobalStyle: typeof import('@celeris/ca-components')['NGlobalStyle']
    NGrid: typeof import('@celeris/ca-components')['NGrid']
    NGridItem: typeof import('@celeris/ca-components')['NGridItem']
    NInput: typeof import('@celeris/ca-components')['NInput']
    NLoadingBarProvider: typeof import('@celeris/ca-components')['NLoadingBarProvider']
    NMenu: typeof import('@celeris/ca-components')['NMenu']
    NMessageProvider: typeof import('@celeris/ca-components')['NMessageProvider']
    NModal: typeof import('@celeris/ca-components')['NModal']
    NNotificationProvider: typeof import('@celeris/ca-components')['NNotificationProvider']
    NPopover: typeof import('@celeris/ca-components')['NPopover']
    NRow: typeof import('@celeris/ca-components')['NRow']
    NScrollbar: typeof import('@celeris/ca-components')['NScrollbar']
    NSelect: typeof import('@celeris/ca-components')['NSelect']
    NSpace: typeof import('@celeris/ca-components')['NSpace']
    NSpin: typeof import('@celeris/ca-components')['NSpin']
    NStatistic: typeof import('@celeris/ca-components')['NStatistic']
    NSwitch: typeof import('@celeris/ca-components')['NSwitch']
    NText: typeof import('@celeris/ca-components')['NText']
    NTooltip: typeof import('@celeris/ca-components')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
